# YAML schema for Docker Compose
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: login-jwt-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-login-jwt
    ports:
      - "5433:5432"
    volumes:
      - ./db_postgres:/var/lib/postgresql/data